### PR TITLE
Packages update (Angular 8)

### PR DESCRIPTION
**Pull request by salnkv**
Update for outdated packages. Angular 8 support

### CODE REVIEW

**Comment by edy-ap** [comment]
thanks,

**Comment by salnkv** [comment]
You are welcome! Can you please update you package in npm?
https://www.npmjs.com/package/ngx-twitter-api

**Comment by edy-ap** [comment]
of course

**Comment by edy-ap** [comment]
https://www.npmjs.com/package/ngx-twitter-api

**Comment by salnkv** [comment]
Thanks man!

**Pull request merged**
